# Generated by Django 2.1.7 on 2020-08-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skillsets',
            field=models.CharField(default='No skill sets assigned', max_length=100),
        ),
    ]
