# Generated by Django 2.1.7 on 2020-08-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_skillsets'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tools',
            field=models.CharField(default='No tools are assigned', max_length=150),
        ),
    ]
