# Generated by Django 2.1.7 on 2020-08-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200801_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='computer_languages_known',
            field=models.CharField(default='Languages are not assigned', max_length=100),
        ),
    ]
