# Generated by Django 2.1.7 on 2020-08-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_computer_languages_known'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(default='EEE', max_length=30),
        ),
    ]
