# Generated by Django 2.2.15 on 2020-08-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='working_at',
            field=models.CharField(default='Not updated yet', max_length=30),
        ),
    ]
