# Generated by Django 2.2.15 on 2020-08-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_working_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='batch',
            field=models.PositiveIntegerField(default=2020),
        ),
    ]
