# Generated by Django 2.2.15 on 2020-08-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(default='notset@gmail.com', max_length=254),
        ),
    ]
